// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace TaffySharp.Lib
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "taffy_ffi";



        [DllImport(__DllName, EntryPoint = "taffytree_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint taffytree_new();

        [DllImport(__DllName, EntryPoint = "taffytree_with_capacity", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint taffytree_with_capacity(nuint capacity);

        [DllImport(__DllName, EntryPoint = "taffytree_new_with_children", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong taffytree_new_with_children(nuint tree, c_Style* style, ulong* children, nuint children_len);

        [DllImport(__DllName, EntryPoint = "taffytree_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void taffytree_free(nuint tree);

        [DllImport(__DllName, EntryPoint = "taffytree_enable_rounding", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void taffytree_enable_rounding(nuint tree);

        [DllImport(__DllName, EntryPoint = "taffytree_disable_rounding", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void taffytree_disable_rounding(nuint tree);

        [DllImport(__DllName, EntryPoint = "taffytree_new_leaf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong taffytree_new_leaf(nuint tree, c_Style* style);

        [DllImport(__DllName, EntryPoint = "taffytree_add_child", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_add_child(nuint tree, ulong parent, ulong child);

        [DllImport(__DllName, EntryPoint = "taffytree_remove", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_remove(nuint tree, ulong node);

        [DllImport(__DllName, EntryPoint = "taffytree_clear", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void taffytree_clear(nuint tree);

        [DllImport(__DllName, EntryPoint = "taffytree_replace_child_at_index", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_replace_child_at_index(nuint tree, ulong parent, nuint index, ulong child);

        [DllImport(__DllName, EntryPoint = "taffytree_remove_child", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_remove_child(nuint tree, ulong parent, ulong child);

        [DllImport(__DllName, EntryPoint = "taffytree_remove_child_at_index", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_remove_child_at_index(nuint tree, ulong parent, nuint index);

        [DllImport(__DllName, EntryPoint = "taffytree_dirty", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_dirty(nuint tree, ulong node);

        [DllImport(__DllName, EntryPoint = "taffytree_mark_dirty", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_mark_dirty(nuint tree, ulong node);

        [DllImport(__DllName, EntryPoint = "taffytree_set_style", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_set_style(nuint tree, ulong node, c_Style* style);

        [DllImport(__DllName, EntryPoint = "taffytree_compute_layout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_compute_layout(nuint tree, ulong node, c_AvailableSpace available_space);

        [DllImport(__DllName, EntryPoint = "taffytree_layout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int taffytree_layout(nuint tree, ulong node, c_Layout* layout);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_Length
    {
        public int dim;
        public float value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_Size
    {
        public c_Length width;
        public c_Length height;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_Rect
    {
        public c_Length left;
        public c_Length right;
        public c_Length top;
        public c_Length bottom;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_GridIndex
    {
        public sbyte kind;
        public short value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_GridPlacement
    {
        public c_GridIndex start;
        public c_GridIndex end;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_GridTrackSize
    {
        public c_Length min_size;
        public c_Length max_size;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_GridTrackSizing
    {
        public int repetition;
        public c_GridTrackSize* single;
        public c_GridTrackSize* repeat;
        public nuint repeat_count;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_Style
    {
        public int display;
        public int item_is_table;
        public int item_is_replaced;
        public int box_sizing;
        public int overflow_x;
        public int overflow_y;
        public float scrollbar_width;
        public int position;
        public c_Rect inset;
        public c_Size gap;
        public int text_align;
        public c_Rect margin;
        public c_Rect border;
        public c_Rect padding;
        public c_Size size;
        public c_Size min_size;
        public c_Size max_size;
        public int flex_wrap;
        public int flex_direction;
        public float flex_grow;
        public float flex_shrink;
        public c_Length flex_basis;
        public c_GridTrackSizing* grid_template_rows;
        public nuint grid_template_rows_count;
        public c_GridTrackSizing* grid_template_columns;
        public nuint grid_template_columns_count;
        public c_GridTrackSize* grid_auto_rows;
        public nuint grid_auto_rows_count;
        public c_GridTrackSize* grid_auto_columns;
        public nuint grid_auto_columns_count;
        public int grid_auto_flow;
        public c_GridPlacement grid_row;
        public c_GridPlacement grid_column;
        public float aspect_ratio;
        public int has_aspect_ratio;
        public int align_items;
        public int has_align_items;
        public int justify_items;
        public int has_justify_items;
        public int align_self;
        public int has_align_self;
        public int justify_self;
        public int has_justify_self;
        public int align_content;
        public int has_align_content;
        public int justify_content;
        public int has_justify_content;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_AvailableSpace
    {
        public c_Length width;
        public c_Length height;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct c_Layout
    {
        public long order;
        public fixed float location[2];
        public fixed float size[2];
        public fixed float content_size[2];
        public fixed float scrollbar_size[2];
        public fixed float border[4];
        public fixed float padding[4];
        public fixed float margin[4];
    }



}
